# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(286, 498)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(10, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.name.setFont(font)
        self.name.setAutoFillBackground(False)
        self.name.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.name.setFrameShape(QtWidgets.QFrame.Box)
        self.name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.name.setLineWidth(3)
        self.name.setMidLineWidth(0)
        self.name.setTextFormat(QtCore.Qt.AutoText)
        self.name.setScaledContents(False)
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setWordWrap(False)
        self.name.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.name.setObjectName("name")
        self.information = QtWidgets.QLabel(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(10, 160, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.information.setFont(font)
        self.information.setStyleSheet("")
        self.information.setAlignment(QtCore.Qt.AlignCenter)
        self.information.setObjectName("information")
        self.temp = QtWidgets.QLabel(self.centralwidget)
        self.temp.setGeometry(QtCore.QRect(10, 200, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.temp.setFont(font)
        self.temp.setStyleSheet("color: rgb(61, 61, 61);")
        self.temp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.temp.setObjectName("temp")
        self.feelTemp = QtWidgets.QLabel(self.centralwidget)
        self.feelTemp.setGeometry(QtCore.QRect(10, 250, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.feelTemp.setFont(font)
        self.feelTemp.setStyleSheet("color: rgb(61, 61, 61);")
        self.feelTemp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.feelTemp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.feelTemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.feelTemp.setObjectName("feelTemp")
        self.maxTemp = QtWidgets.QLabel(self.centralwidget)
        self.maxTemp.setGeometry(QtCore.QRect(10, 300, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.maxTemp.setFont(font)
        self.maxTemp.setStyleSheet("color: rgb(61, 61, 61);")
        self.maxTemp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.maxTemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.maxTemp.setObjectName("maxTemp")
        self.minTemp = QtWidgets.QLabel(self.centralwidget)
        self.minTemp.setGeometry(QtCore.QRect(10, 350, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.minTemp.setFont(font)
        self.minTemp.setStyleSheet("color: rgb(61, 61, 61);")
        self.minTemp.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.minTemp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.minTemp.setObjectName("minTemp")
        self.pressure = QtWidgets.QLabel(self.centralwidget)
        self.pressure.setGeometry(QtCore.QRect(10, 400, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pressure.setFont(font)
        self.pressure.setStyleSheet("color: rgb(61, 61, 61);")
        self.pressure.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.pressure.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pressure.setObjectName("pressure")
        self.tempOut = QtWidgets.QLabel(self.centralwidget)
        self.tempOut.setGeometry(QtCore.QRect(180, 210, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tempOut.setFont(font)
        self.tempOut.setText("")
        self.tempOut.setObjectName("tempOut")
        self.feelOut = QtWidgets.QLabel(self.centralwidget)
        self.feelOut.setGeometry(QtCore.QRect(150, 260, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.feelOut.setFont(font)
        self.feelOut.setText("")
        self.feelOut.setObjectName("feelOut")
        self.maxTempOut = QtWidgets.QLabel(self.centralwidget)
        self.maxTempOut.setGeometry(QtCore.QRect(140, 310, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.maxTempOut.setFont(font)
        self.maxTempOut.setText("")
        self.maxTempOut.setObjectName("maxTempOut")
        self.minTempOut = QtWidgets.QLabel(self.centralwidget)
        self.minTempOut.setGeometry(QtCore.QRect(130, 360, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.minTempOut.setFont(font)
        self.minTempOut.setText("")
        self.minTempOut.setObjectName("minTempOut")
        self.pressureOut = QtWidgets.QLabel(self.centralwidget)
        self.pressureOut.setGeometry(QtCore.QRect(140, 410, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pressureOut.setFont(font)
        self.pressureOut.setText("")
        self.pressureOut.setObjectName("pressureOut")
        self.inputCity = QtWidgets.QLabel(self.centralwidget)
        self.inputCity.setGeometry(QtCore.QRect(10, 60, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputCity.setFont(font)
        self.inputCity.setStyleSheet("color: rgb(61, 61, 61);")
        self.inputCity.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.inputCity.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputCity.setObjectName("inputCity")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 70, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(61, 61, 61);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.find = QtWidgets.QPushButton(self.centralwidget)
        self.find.setGeometry(QtCore.QRect(10, 120, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.find.setFont(font)
        self.find.setStyleSheet("color: rgb(61, 61, 61);")
        self.find.setObjectName("find")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(10, 450, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("color: rgb(61, 61, 61);")
        self.result.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.resultOut = QtWidgets.QLabel(self.centralwidget)
        self.resultOut.setGeometry(QtCore.QRect(150, 460, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.resultOut.setFont(font)
        self.resultOut.setText("")
        self.resultOut.setObjectName("resultOut")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Current Weather"))
        self.name.setText(_translate("MainWindow", "Текущая погода"))
        self.information.setText(_translate("MainWindow", "Информация"))
        self.temp.setText(_translate("MainWindow", "Температура:"))
        self.feelTemp.setText(_translate("MainWindow", "Ощущается:"))
        self.maxTemp.setText(_translate("MainWindow", "Максимум:"))
        self.minTemp.setText(_translate("MainWindow", "Минимум:"))
        self.pressure.setText(_translate("MainWindow", "Давление:"))
        self.inputCity.setText(_translate("MainWindow", "Введите город:"))
        self.find.setText(_translate("MainWindow", "Найти"))
        self.result.setText(_translate("MainWindow", "Результат:"))
